# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

# Define the number of master and worker nodes
# If this number is changed, remember to update setup-hosts.sh script with the new hosts IP details in /etc/hosts of each VM.
NUM_MANAGER_NODE = 1
MANAGER_IP = "192.168.5.2"
IP_RANGE="192.168.5"
NUM_WORKERS = 2
VM_MEMORY = 512
NUM_CPU = 1

instances = []

(1..NUM_WORKERS).each do |n|
  instances.push({:name => "worker-#{n}", :ip => "192.168.10.#{n*2 + 3}", :num => "#{n}"})
end

File.open("./conf/hosts", 'w') { |file|
  instances.each do |i|
    file.write("#{i[:ip]} #{i[:name]} #{i[:name]}\n")
  end
}

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |v|
    v.memory = VM_MEMORY
    v.cpus = NUM_CPU
  end

  (1..NUM_MANAGER_NODE).each do |i|
    config.vm.define "manager" do |node|
      node.vm.hostname = 'manager'
      node.vm.provider "virtualbox" do |vb|
          vb.name = "swarm-manager"
          vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
      end
      node.vm.network :private_network, ip: "#{MANAGER_IP}"
      node.vm.network "forwarded_port", guest: 22, host: "#{2720 + i}"
      node.vm.provision "install-docker", type: "shell", :path => "ubuntu/install-docker.sh"
      node.vm.provision "docker-daemon", type: "shell", :path => "ubuntu/docker-daemon.sh"
      node.vm.provision "docker-test", type: "shell", :path => "ubuntu/docker-test.sh"
      if File.file?("./conf/hosts")
        node.vm.provision "file", source: "./conf/hosts", destination: "/tmp/hosts"
        node.vm.provision "shell", inline: "cat /tmp/hosts >> /etc/hosts", privileged: true
      end
      node.vm.provision "shell", inline: "docker swarm init --advertise-addr #{MANAGER_IP}"
      node.vm.provision "shell", inline: "docker swarm join-token -q worker > /vagrant/conf/token"
    end
  end

  instances.each do |instance|
    config.vm.define instance[:name] do |node|
      number = instance[:num]
      ssh_forward = "#{2725 + number.to_i + 2}".to_i
      ip = "#{instance[:ip]}"
      token = "/vagrant/conf/token"
      node.vm.hostname = instance[:name]
      node.vm.provider "virtualbox" do |vb|
          vb.name = instance[:name]
          vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
      end
      node.vm.network :private_network, ip: "#{instance[:ip]}"
      node.vm.network "forwarded_port", guest: 22, host: ssh_forward
      node.vm.provision "install-docker", type: "shell", :path => "ubuntu/install-docker.sh"
      node.vm.provision "docker-daemon", type: "shell", :path => "ubuntu/docker-daemon.sh"
      node.vm.provision "docker-test", type: "shell", :path => "ubuntu/docker-test.sh"
      if File.file?("./conf/hosts")
        node.vm.provision "file", source: "./conf/hosts", destination: "/tmp/hosts"
        node.vm.provision "shell", inline: "cat /tmp/hosts >> /etc/hosts", privileged: true
      end
      node.vm.provision 'shell', path: 'ubuntu/worker-join.sh',
        args: [ip, token, MANAGER_IP],
        privileged: true
    end
  end

end
