# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

# Define the number of master and worker nodes
# If this number is changed, remember to update setup-hosts.sh script with the new hosts IP details in /etc/hosts of each VM.
NUM_NODE = 1

IP_NW = "192.168.5.56"


Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false

  (1..NUM_NODE).each do |i|
      config.vm.define "docker" do |node|
        # Name shown in the GUI
        node.vm.provider "virtualbox" do |vb|
            vb.name = "docker"
            vb.memory = 1024
            vb.cpus = 2
        end
        node.vm.hostname = "docker"
        node.vm.network :private_network, ip: IP_NW
        node.vm.network "forwarded_port", guest: 22, host: "#{2720 + i}"
        node.vm.provision "install-docker", type: "shell", :path => "ubuntu/install-docker.sh"
        node.vm.provision "test-docker", type: "shell", :path => "ubuntu/test-docker.sh"
      end
  end
end